### ISSUE TITLE
html comments

### ISSUE THREAD

**Issue by gforceg** [fireside21/vscode-cshtml#1]
Sometimes I need HTML comments rather than razor comments. I am not sure if there would be an easy way to add yet another hot key for commenting.

When I try to use razor comments in the HTML portions of a .cshtml file the comments are rendered by the browser.

**Comment by michaelblyons** [comment]
This package isn't focused on Razor. Phil Haack has [a good comparison table][2] of the syntax for various constructs. If you're using the syntax from the center column instead of the right column, this might not be the extension you're looking for (which might be [Austin's package][1] instead).

[1]: https://marketplace.visualstudio.com/items?itemName=austincummings.razor-plus
[2]: https://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/

**Comment by gforceg** [comment]
Good call!
